version: "3.8"
services:
  app:
    build: .
    container_name: cdr-token
    restart: always
    environment:
      - NODE_ENV=production
    expose:
      - "3334"

  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
